### ISSUE TITLE
Cantidad de Integrantes en el Equipo

### ISSUE THREAD

**Issue by LucioMSP** [GitHub-Campus-Program-LATAM/CIS#1]
Hola,

El detalle que tenemos todos es: ¿de cuantos se pueden integrar los equipos para el Hack?

¡Saludos!

**Comment by DaviiidSG** [comment]
Según lo que yo entendí no hay un límite, pero si hay muchas personas en un mismo equipo se hace más difícil trabajar de manera organizada

**Comment by GonzaloAqui** [comment]
Aprovechando el hilo **¿Alguien que sea parte de la comunidad LAUNCH_X_LATAM?** que quiera y tenga una idea que hagamos como proyecto para este hackathon para representarnos como comunidad... Si es así agrégame éxito a todos y nos vemos allá.

**Comment by DaviiidSG** [comment]
@GonzaloAqui yo formo parte de LaunchX, aún estoy pensando en una idea interesante de proyecto pero me gustaría formar equipo con miembros de la comunidad y armar un proyecto que nos represente

**Comment by DiegoAlexanderCorchueloAyala** [comment]
Igualmente formo parte de LaunchX, si quieren creamos un grupo en discord o zoom para poder dialogar.

**Comment by DaviiidSG** [comment]
@DiegoAlexanderCorchueloAyala claro! este es mi usuario de discord @Daviddd#0807 puedes comunicarte conmigo por ahí sobre el proyecto :)

**Comment by lasr21** [comment]
> Hola,
> 
> El detalle que tenemos todos es: ¿de cuantos se pueden integrar los equipos para el Hack?
> 
> ¡Saludos!

Es correcto no hay limite pero tengan presente que entre más mas complicado la orgnización.

**Comment by LucioMSP** [comment]
Gracias Luis!

**Comment by GonzaloAqui** [comment]
@DaviiidSG Gracias, es cuestión de conversarlo para hacerlo real, aunque yo no uso discord por que medio seria la comunicación?

**Comment by jalukone** [comment]
@lasr21 la fecha limite es hasta el 8 de noviembre ?

**Comment by DaviiidSG** [comment]
@GonzaloAqui contáctame por teams, creo que te encontré jajajaj
