### ISSUE TITLE
Oscar Tinajero's Portfolio

### ISSUE THREAD

**Issue by OscarTinajero117** [GitHub-Campus-Program-LATAM/CIS#13]
### ¿Asististe al taller de GitHub?

- [X] He asistido al Workshop de GitHub

### Nombre del proyecto

OscarTinajero117.github.io

### Repositorio del proyecto

https://github.com/OscarTinajero117/OscarTinajero117.github.io

### Project URL

http://oscartinajero117.me/

### Nombre de la Universidad/instituación

LaunchX LATAM

### Descripción del Proyecto

Por falta de tiempo no pude realizar el app que quería, pero en la transmisión me llamó mucho la atención el uso de NameCheap, así que use namecheap y Bootstrap Studio con las licencias de la GSDP para realizar mi portafolio.

### Herramientas del GitHub Student Developer Pack Tools usadas

GitHub, Other

**Comment by lasr21** [comment]
Hola @OscarTinajero117  Muchas gracias por tu proyecto. Vamos a revisar todos los proyectos y anunciar a los ganadores el viernes 18 de noviembre. Mientras tanto si tu proyecto fue en equipo por favor menciona a los integrantes de tu equipo antes del Miercoles 16 de noviembre.

**Comment by OscarTinajero117** [comment]
@lasr21 tengo una pregunta, ya mandaron las constancias de participación? es que aún no me llega a mí 😢

**Comment by OscarTinajero117** [comment]
@lasr21 por que medio se anunciara al ganador? 😃
